blog1/urls.py
from django.urls import path
from django.shortcuts import render
from . import views

namespace='blog1'
urlpatterns=[
    path('',views.home,name='home'),
    path('<slug:slug>/',views.postcategory,name='postcategory'),
    path('<str:slug>',views.postdetail,name='postdetail'),
]

home/urls.py
from django.urls import path
from . import views

namespace="home"
urlpatterns=[
    path('',views.homepage,name='home'),
    path('register',views.signup,name='register'),
    path('login',views.login,name='login'),
    path('logout',views.logout,name='logout'),
    path('search',views.search,name='search'),
    path('contactus',views.Contactus,name='contactus'),
    path('aboutus',views.aboutus,name='aboutus'),
]

newblog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('home.urls','home'),namespace='home')),
    path('blog/',include(('blog1.urls','blog1'),namespace='blog1')),
    path('video/',include(('video.urls','video'),namespace='video')),
    path('products/',include(('products.urls','products'),namespace='products')),
    
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):
    name=models.CharField(max_length=100)
    username=models.CharField(max_length=50)
    contactn=models.IntegerField()
    email=models.EmailField(max_length=100)
    msg=models.CharField(max_length=1000)

    def __str__(self):
        return self.username + " " + self.msg[:10]

home/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate
from django.contrib.auth.models import User,auth
from django.contrib import messages
from blog1.models import Post
from home.models import Contact

# Create your views here.
def homepage(request):
    return render(request,'home/index.html')

def signup(request):
    if request.method=='POST':
        firstname=request.POST['first_name']
        lastname=request.POST['last_name']
        username=request.POST['username']
        password=request.POST['password1']
        cpassword=request.POST['password2']
        email=request.POST['email']
        if firstname=="":
            messages.error(request,"First name is must")
            return redirect('/register')
        elif lastname=="":
            messages.error(request,"Last name is must")
            return redirect('/register')
        elif username=="":
            messages.error(request,"Username is must")
            return redirect('/register')
        elif len(username)>7:
            messages.error(request,"username should not be more than 7 characters") 
            return redirect('/register')  
        elif email=="":
            messages.error(request,"Email is must")
            return redirect('/register')
        elif password=="":
            messages.error(request,"Password is must")
            return redirect('/register')
        elif lastname=="":
            messages.error(request,"Confirm Password is must")
            return redirect('/register')
        elif password!=cpassword:
            messages.error(request,"Password didn't match")
            return redirect('/register')
        else:
            if User.objects.filter(username=username).exists():
                messages.error(request,"Username already exists")
                return redirect('/register')
            elif User.objects.filter(email=email).exists():
                messages.error(request,"Email already exists")
                return redirect('/register')
            user=User.objects.create_user(username=username,password=password,email=email,first_name=firstname,last_name=lastname)
            user.save()
            messages.info(request,"Registered Successfully")
            auth.login(request,user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('/')
    else:
        return render(request,'home/register.html')

def login(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        user=auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request,user)
            messages.info(request,"Login Successful")
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('/')
        else:
            messages.error(request,"Check Username or Password")
            return redirect('/login')
    else:
        return render(request,'home/login.html')
        
    
def logout(request):
    auth.logout(request)
    return redirect("/")

def search(request):
    query=request.GET['query']
    if(len(query)>60):
        posts=Post.objects.none()
    else:
        posttitles=Post.objects.filter(title__icontains=query)
        postcontents=Post.objects.filter(desc__icontains=query)
        posts=posttitles.union(postcontents)
    if posts.count()==0:
        messages.warning(request,"No search result found")
    context={'posts':posts,'query':query}
    return render(request,"home/search.html",context)

def Contactus(request):
    if request.method=='POST':
        name=request.POST['name']
        username=request.POST['username']
        email=request.POST['email']
        contact=request.POST['contact']
        msg=request.POST['message']
        c=Contact(name=name,username=username,contactn=contact,email=email,msg=msg)
        c.save()
        messages.success(request,"Thanks for contacting. We will inform you soon")
        return redirect('/contactus')
    else:
        return render(request,'home/contactus.html')

def aboutus(request):
    return render(request,'home/aboutus.html')

templates/home/aboutus.html
{% extends 'base.html' %}
{% block content %}
<div class='container'>
<div class='row'>
<div class='col'>
<h2>About Us</h2>
<li>Admin: AMIT</li>
<li>Email: amitkatoch4u@gmail.com</li>
</div>
</div>
</div>
{% endblock content %}

templates/home/contactus.html
{% extends 'base.html' %}
{% block title %}Contact us{% endblock title %}
{% block content %}
<div class="container">
    <h1>Contact  MySite Admin</h1>
    <form method="post" action="contactus">
        {% csrf_token %}
        <div class="form-group">
            <label for="name">Name</label>
            <input type="text" id="name" name="name" class="form-control" aria-describedby="name" required>
            </div>
        <div class="form-group">
          <label for="user">Username</label>
          <input type="text" class="form-control" id="user" name="username" required>
        </div>
        <div class="form-group">

          <label for="email">Email address</label>
          <input type="email" class="form-control" id="email" name="email" aria-describedby="emailHelp" required>
          <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
        </div>
        <div class="form-group">
          <label for="phone">Phone Number</label>
          <input type="phone" class="form-control" id="phone" name="contact" required>
        </div>
        <div class="form-group">
          <label for="content">Describe your issue:</label>
          <textarea class="form-control" name="message" id="content" cols="30" rows="6" required></textarea>
        </div>
       
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
</div>
{% endblock content%} 

templates/home/index.html
{% extends 'base.html' %}
{% load static %}

templates/home/login.html
{% extends 'base.html'%}
{% load static %}
{% block mycss%}<style>
        
        .loginimage{
            margin:0 auto;
            height:200px;

        }

        .loginimage img{
            width:200px;
            height:200px;
        }
        .maindiv{
            background:linear-gradient(90deg,rgba(54,217,182,1) 0%, rgba(32,112))
            width:100%;
            margin: 0 auto;
            height:400px;
            padding:40px;
            display:grid;
            grid-template-column: 1fr 1fr;
            grid-template-rows: 1fr 1fr;
            box-shadow: 0 14px 28px rgba(0,0,0,0.25),0 10px 10px rgba(0,0,0,0.25)
        }
        .loginform form{
            width: 100%,
            margin: auto;
            padding: 40px;
            padding-bottom: 0px;
            border-bottom: 1px solid #e9e9e9;
            background-color: #fff;
            box-shadow: 0 3px 8px rgba(0,0,0,0.25);

        }
        .loginform form input{
            padding-top:5px;
            padding-bottom:5px;
            padding-right: 50px;
            padding-left: 5px;
        }   
        #loginbtn{
            padding:10px 50px;
            margin: 20px auto;
            width: 80%;
            background: orangered;
            font-weight:bold;
            
        }
    </style>{%endblock mycss%}
{% block content %}
{% for message in messages %}

<p>{{message}}</p>
{% endfor %}
<div class='container'>
<div class='row'>
<div class='col'>
<form action='login' method='POST'>
{% csrf_token %}
{% if request.GET.next %}
<input type="hidden" name="next" value="{{request.GET.next}}">
{% endif %}
<div>
                          <label><span>Enter Username</span><input type='text' name="username"></label>
                        </div>
                        <div>
                           <label><span>Enter Password<input type='password' name='password'></span></label>
                                   </div>
                                   <div>
                                   <button id="loginbtn" type="submit">LOGIN</button>
                                </div>
              
</form>
</div>
</div>
</div>
{% endblock content %}

templates/home/register.html
{% extends 'base.html' %}
{% load static %}
{% block mycss %}<style>
   
    input{
        padding: 5px 25px;
    }
    form p{

       margin-bottom: -1px;
    }
    #p1,#p2,#p3{
margin-left: 185px;
width: 130px;
padding:4px 0px;
}
#p4{
margin-left:170px;
padding:4px 0px;
        width:120px;
    }
#p5{
margin-left:189px;
padding:4px 0px;
        width:120px;
    }
#p6{
margin-left:204px;
padding:4px 0px;
        width:160px;
    
    
    }
    #p2,#p3,#p4,#p5,#p6{
        margin-top: 3px;
    }
    .formbtn{
        margin-top:30px;
        margin-bottom:10px;

    }
    .formbtn input{
       font-weight: bold;
       font-size:20px;
       padding:7px 110px;
       background-color: green;
          
          border-radius: 20%;
          color: white;
    }

</style>{%endblock mycss%}
{% block content %}
<div class="container">
    <div class="jumbotron">
       <div class="container" style="width: 70%; margin:auto; padding:30px; text-align:center">
          <form action="register" method="POST">
              {% csrf_token %}
              {% if request.GET.next %}
              <input type="hidden" name="next" value="{{request.GET.next}}">
              {% endif %}
              <p id="p1">First Name</p>
              <input type="text" name="first_name" placeholder="First Name" >
              <p id="p2">Last Name</p>
              <input type="text" name="last_name" placeholder="Last Name" >
              <p id="p3">Username</p>
              <input type="text" name="username" placeholder="Username" >
              <p id="p4">Email</p>
              <input type="text" name="email" placeholder="Email" >
              <p id="p5">Password</p>
              <input type="text" name="password1" placeholder="Password" >
              <p id="p6">Confirm Password</p>
              <input type="text" name="password2" placeholder="Confirm Password">
              <div class="formbtn">
                  <input type="submit">
              </div>
            </form>
          </div>
        </div>
        </div>
      <div>

      <h3> Request object attributes</h3>
      <ul>
      <li>{{request.scheme}}</li>
      <li>{{request.method}}</li>
      <li>{{request.path}}</li>
      <li>{{request.GET}}</li>
      <li>{{request.POST}}</li>
      <li>{{request.user}}</li>
      </ul>
      </div>
{% endblock content %}

templates/home/search.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
<div class="row">
<div class="col">

{% if posts|length < 1 %}
<p>No search Result Found</p>
<p>Your search query- <b>{{query}}</b> did'nt match any documents...</p>
{% endif %}
{% for p in posts %}
<h2><a href="{% url 'blog1:postdetail' p.slug %}"{{p.title}}</h2>
<span>Author:{{p.author}}</span>
<p>{{p.desc}}</p>
{% endfor %}
</div>
</div>
</div>
{% endblock content %}