home/urls.py
from django.urls import path
from . import views

namespace="home"
urlpatterns=[
    path('',views.homepage,name='home'),
    path('register',views.signup,name='register'),
    path('login',views.login,name='login'),
    path('logout',views.logout,name='logout'),
    path('search',views.search,name='search'),
    path('contactus',views.Contactus,name='contactus'),
    path('aboutus',views.aboutus,name='aboutus'),
]

newblog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('home.urls','home'),namespace='home')),
    path('blog/',include(('blog1.urls','blog1'),namespace='blog1')),
    path('video/',include(('video.urls','video'),namespace='video')),
    path('products/',include(('products.urls','products'),namespace='products')),
    
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views

namespace='products'
urlpatterns = [
    path('',views.productcategory,name='productcat'),
    path('<slug:slug>/', views.products, name='products'),
]

products/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    title=models.CharField(max_length=30)
    img=models.ImageField(upload_to='prdct')
    slug=models.SlugField(unique=True)

    def __str__(self):
        return self.title

class Product(models.Model):
    name=models.CharField(max_length=100)
    image=models.ImageField(upload_to='pixx')
    slug=models.SlugField(unique=True)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    url=models.URLField()
    description = models.TextField()
    
    def __str__(self):
        return self.name

products/views.py
from django.shortcuts import render
from products.models import Product,Category
# Create your views here.

def productcategory(request):
    categories=Category.objects.all()
    context={"categories":categories} 
    return render(request,'products/productcat.html',context)
    

def products(request,slug):
    category=Category.objects.filter(slug=slug).first()
    productss = Product.objects.filter(category=category)
    context={'productss':productss}
    return render(request, 'products/products.html', context)

templates/products/productcat.html
{% extends 'base.html' %}
{% block content %}
<div class="container py-4">
    <div class="row">
    <h2>Product Categories</h2>
    {% for c in categories %}
    
    <div class="col-md-4">
    <h4><a href="{% url 'products:products' c.slug %}">{{c.title}}</a></h4>
    
    <img class="rounded mx-auto d-block" src="{{c.img.url}}">
    </div>
    {% endfor %}
    </div>
    </div>
{% endblock content %}

templates/products/products.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<h1 style="text-align:center;">Products</h1>
<div class="card" style="width: 18rem;">
{% for p in productss %}
<div class="col-md-4"></div>
  
  <div class="card-body">
    <h5 class="card-title">{{ p.name }}</h5>
    <img class="rounded mx-auto d-block" src="{{p.image.url}}" style="width: 200px;">
    <p class="card-text">{{ p.description }}</p>
    <p class="card-text">Price - Rs {{ p.price }}/-</p>
    <a href={{p.url}} class="btn btn-primary">Buy Now</a>
  </div>

  {% endfor %}
  
</div>
{% endblock content %}