home/urls.py
from django.urls import path
from . import views

namespace="home"
urlpatterns=[
    path('',views.homepage,name='home'),
    path('register',views.signup,name='register'),
    path('login',views.login,name='login'),
    path('logout',views.logout,name='logout'),
    path('search',views.search,name='search'),
    path('contactus',views.Contactus,name='contactus'),
    path('aboutus',views.aboutus,name='aboutus'),
]

newblog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('home.urls','home'),namespace='home')),
    path('blog/',include(('blog1.urls','blog1'),namespace='blog1')),
    path('video/',include(('video.urls','video'),namespace='video')),
    path('products/',include(('products.urls','products'),namespace='products')),
    
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

video/urls.py
from django.urls import path
from . import views

namespace="video"
urlpatterns = [
    path('',views.categorylist,name='catlist'),
    path('postComment',views.comments,name="postComment"),
    path('<slug:slug>',views.videodetail,name='videodetail'),
    path('<slug:slug>/',views.categoryvideos,name='catvideo'),
]

video/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from embed_video.fields import EmbedVideoField
from django.contrib.auth.models import User
from django.utils.timezone import now
# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=30)
    img=models.ImageField(upload_to='videocatpics',blank=True)
    slug=models.SlugField(unique=True)

    def __str__(self):
        return self.name

class Item(models.Model):
    title=models.CharField(max_length=100)
    slug=models.SlugField(unique=True)
    img=models.ImageField(upload_to='videothumbnail')
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    video=EmbedVideoField()
    desc=models.TextField()
    publish=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

class VideoComment(models.Model):
    srno=models.AutoField(primary_key=True)
    comment=models.TextField()
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    video=models.ForeignKey(Item,on_delete=models.CASCADE)
    parent=models.ForeignKey('self',on_delete=models.CASCADE,null=True)
    timestamp=models.DateTimeField(default=now)

    def __str__(self):
        return self.comment[:15] + "by" + self.user.username

video/views.py
from django.contrib import messages
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from video.models import Category,Item,VideoComment
# Create your views here.
def categorylist(request):
    categories=Category.objects.all()
    context={"categories":categories} 
    return render(request,'video/categorylist.html',context)

def categoryvideos(request,slug):
    category=Category.objects.filter(slug=slug).first()
    catvideos=Item.objects.filter(category=category)
    context={'catvideos':catvideos}
    return render(request,'video/catvideo.html',context)

def videodetail(request,slug):
    video=Item.objects.filter(slug=slug).first()
    comments=VideoComment.objects.filter(video=video,parent=None)
    replies=VideoComment.objects.filter(video=video).exclude(parent=None)
    repDict={}
    for reply in replies:
        if reply.parent.srno not in repDict.keys():
            repDict[reply.parent.srno]=[reply]
        else:
            repDict[reply.parent.srno].append(reply)
    context={"videos":video,'comments':comments,'user':request.user,'repDict':repDict}
    # print(comments)
    # print(repDict)
    return render(request,'video/videodetail.html',context)

def comments(request):
    
    videocomment=request.POST.get('commentbox')
    user=request.user
    videosno=request.POST.get('videoSno')
    video=Item.objects.get(id=videosno)
    parentSno=request.POST.get('parentSno')
    if parentSno=="":
        comment1=VideoComment(comment=videocomment,user=user,video=video)
        comment1.save()
        messages.success(request,"Your comment has been posted")
        return HttpResponseRedirect(reverse('video:videodetail',args=(video.slug,)))
    else:
        parent=VideoComment.objects.get(srno=parentSno)
        comment1=VideoComment(comment=videocomment,user=user,video=video,parent=parent)
        comment1.save()
        messages.success(request,"Your reply has been added")
        return HttpResponseRedirect(reverse('video:videodetail',args=(video.slug,)))

templates/video/categorylist.html
{% extends 'base.html' %}
 {% block content %}
 <div class="container py-4">
 <div class="row">
 <h2 style="text-align:center;">Video Categories</h2>
 {% for c in categories %}
 
 <div class="col-md-4">
 <h4><a href="{% url 'video:catvideo' c.slug %}">{{c.name}}</a></h4>
 
 <img style="height:200px;width:300px;" src="{{c.img.url}}">
 </div>
 {% endfor %}
 </div>
 </div>
 {% endblock content %}

templates/video/catvideo.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
<div class="row">
{% for video in catvideos %}
<div class="col-md-4"></div>
<h3>{{video.title}}</h3>
<span>{{video.desc}}</span>
<img style="height:120px;width:150px;" src="{{video.img.url}}">
<a href="{% url 'video:videodetail' video.slug %}">Click to open video</a>
</div>
{% endfor %}
</div>
{% endblock content %}

templates/video/videodetail.html
{% extends 'base.html' %}
{% load static %}
{% load embed_video_tags %}
{% load extras %}
{% block content %}
<div class="container">
<div class="row">
<div class="col">
<h1>{{videos.title}}</h1>
<div class="container embed-responsive embed-responsive-16by9 px-3 py-4" id="vid">
                   {% video videos.video 'small' %}
                </div>
</div>
</div>
<div class='row'>
{% if user.is_authenticated %}
<div>
<form action="/video/postComment" method='post'>
{% csrf_token %}
Post a Comment<input type='text' name="commentbox">
<input type="hidden" name="parentSno" value="">
<input type="hidden" name="videoSno" value="{{videos.id}}">
<input type="submit" value='Post Comment'>
</form>
</div>
{% else %}
<div class='col'>
<h2><a href="{% url 'home:login' %}?next={% firstof request.path '/'%}">Login</a> or <a href="{% url 'home:register' %}?next={% firstof request.path '/' %}">Signup</a> to Comment</h2>

</div>
{% endif %}
</div>
<div class="row">
<h3>{{comment.count}} {% if comments.count == 0 %} No Comments{% elif comments.count == 1 %}Comment {% else%}Comments {% endif %}</h3>
{% for comment in comments %}

<div class="col-md-4">
<img style="height:50px;width:50px;" src="{% static 'images/user.png'%}">
</div>
<div class="col-md-10">
<li>{{comment.user.username}}  <span> {{comment.timestamp}}</span></li>
<p>{{comment.comment}}</p>
</div>
<div class="reply mx-0">
                    {% comment %} {% if user.is_authenticated %} {% endcomment %}
                     {% comment %} <button class="btn btn-sm btn-primary" type="button" data-toggle="collapse" data-target="#replyBox{{comment.id}}" aria-expanded="true" aria-controls="replyBox{{comment.id}}">
                        Reply
                    </button>
                    <div class="collapse" id="replyBox{{comment.id}}"> {% endcomment %}
                        <div class="card card-body my-2"> 
                            <form action="/video/postComment" method='post'>
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Post a reply</label>
                                    <input type="text" class="form-control" name="commentbox" placeholder="Enter comment here">
                                <input type="hidden" name="parentSno" value="{{comment.srno}}">
                
                                </div>
                            <input type="hidden" name="videoSno" value="{{videos.id}}">
                            <button type="submit" class="btn btn-primary">Submit</button>
                            </form>
                        </div>
                    </div>
                    {% comment %} {% else %} {% endcomment %}
                    <button class="btn btn-sm btn-primary" type="button" data-toggle="collapse" data-target="#replyBox{{comment.srno}}" aria-expanded="false" aria-controls="replyBox{{comment.srno}}" disabled>
                       Reply
                    </button>
                    {% comment %} {% endif %} {% endcomment %}
                    <div class="replies my-2">
                        {% for reply in repDict|get_val:comment.srno %}
                        <div class="row">
                            <div class="col-md-1">
                                <img class="rounded mx-auto d-block" src="/static/images/user.png" alt="" style="width: 67px;"> 
                            </div>
                            <div class="col-md-11">
                                <b>{{reply.user.username}}</b> &nbsp; <span class="badge badge-secondary" style="font-size: 13px;">{{reply.timestamp}}</span>
                                <div>{{reply.comment}}</div>

                        </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>



</div>
{% endfor %}
</div>

{% endblock content %}